version: "3.1"
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: timetell
      POSTGRES_USER: timetell
      POSTGRES_PASSWORD: insecure
  importer:
    build: ./src/importer
    links:
      - database:database
    environment:
      DATABASE_NAME: 
      DATABASE_USER: timetell
      DATABASE_PASSWORD: insecure
      DATABASE_PORT: 5432
      DATABASE_HOST: database
      SQL_QUERY: 
      OBJECTSTORE_CONTAINER: 
      OBJECTSTORE_PROJECT_ID:
      OBJECTSTORE_USERNAME:
      OBJECTSTORE_PASSWORD:
  web:
    build: ./src
    ports:
      - "8113:8000"
    links:
      - database
    environment:
      DATABASE_NAME: timetell
      DATABASE_USER: timetell
      DATABASE_PASSWORD: insecure
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "ois_projects_employees.wsgi:application"
      UWSGI_PROCESSES: 4
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/static=/static"