version: "3.0"
services:

  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: timetell
      POSTGRES_USER: timetell
      POSTGRES_PASSWORD: timetell

  example:
    build:
      context: .
    depends_on:
      - database
    ports:
      - "8133:8000"
    environment:
      DB_DATABASE: timetell
      DB_USER: timetell
      DB_PASSWORD: timetell
      DB_HOST: database
      DB_PORT: 5432
    command: ["timetelld", "--config-path", "exampleconfig.yml"]

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - database
    environment:
      DB_DATABASE: timetell
      DB_USER: timetell
      DB_PASSWORD: timetell
      DB_HOST: database
      DB_PORT: 5432
    command: ["make", "test"]
