version: "3.1"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: timetell
      POSTGRES_USER: timetell
      POSTGRES_PASSWORD: insecure
  import:
    build: ./src/import
    links:
      - database:database
    environment:
      DATABASE_NAME: 
      DATABASE_USER: timetell
      DATABASE_PASSWORD: insecure
      DATABASE_PORT: 5432
      DATABASE_HOST: database
      SQL_QUERY: 
      OBJECTSTORE_CONTAINER: 
      OBJECTSTORE_PROJECT_ID:
      OBJECTSTORE_USERNAME:
      OBJECTSTORE_PASSWORD:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
  postgraphile:
    restart: always
    image: graphile/postgraphile
    depends_on:
      - database
    networks:
      - default
    ports:
      - 5000:5000
    command: [
      "postgraphile", 
      "--watch", 
      #"--jwt-token-identifier","public.jwt_token",
      "--connection","postgres://timetell:insecure@database:5432/timetell", 
      #"--jwt-secret","123456789",
      #"--default-role","anonymous", 
      "--schema", "public"] 