version: "3.0"
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: timetell
      POSTGRES_USER: timetell
      POSTGRES_PASSWORD: insecure
  importer:
    build: ./src/import
    links:
      - database:database
    environment:
      DATABASE_NAME: timetell
      DATABASE_USER: timetell
      DATABASE_PASSWORD: insecure
      DATABASE_PORT: "5432"
      DATABASE_HOST: database
      OBJECTSTORE_PROJECT_ID:
      OBJECTSTORE_USERNAME:
      OBJECTSTORE_PASSWORD: