$schema: 'http://json-schema.org/draft-07/schema#'

type: object

properties:
  logging:
    $ref: '#/definitions/logging.dictconfig'
  web:
    $ref: '#/definitions/web'

required:
- logging
- web


definitions:

  web:
    additionalProperties: false
    properties:
      bindport:
        type: integer
        minimum: 1024
        maximum: 65535
      bindaddress:
        type: string
      apikey:
        type: string
      baseurl:
        type: string
        pattern: '/$'  # must end in a slash
    required:
    - apikey
    type: object

  logging.dictconfig:
    additionalProperties: false
    properties:
      disable_existing_loggers:
        type: boolean
      filters:
        patternProperties:
          ^[a-zA-Z0-9._-]+$:
            additionalProperties: false
            properties:
              name:
                type: string
            type: object
        type: object
      formatters:
        patternProperties:
          '^[a-zA-Z0-9._-]+$':
            additionalProperties: false
            properties:
              datefmt:
                type: string
              format:
                type: string
            type: object
        type: object
      handlers:
        patternProperties:
          '^[a-zA-Z0-9._-]+$':
            properties:
              class:
                type: string
              filters:
                items:
                  type: string
                type: array
                uniqueItems: true
              formatter:
                type: string
              level:
                type: string
            required:
              - class
            type: object
        type: object
      incremental:
        type: boolean
      loggers:
        patternProperties:
          ^[a-zA-Z0-9._-]+$:
            properties:
              filters:
                items:
                  type: string
                type: array
                uniqueItems: true
              handlers:
                items:
                  type: string
                type: array
                uniqueItems: true
              level:
                type: string
              propagate:
                type: boolean
            type: object
        type: object
      root:
        properties:
          filters:
            items:
              type: string
            type: array
            uniqueItems: true
          handlers:
            items:
              type: string
            type: array
            uniqueItems: true
          level:
            enum:
              - CRITICAL
              - ERROR
              - WARNING
              - INFO
              - DEBUG
            type: string
        type: object
      version:
        enum:
          - 1
        type: integer
    required:
      - version
    type: object
